### ISSUE TITLE
Kernel patching for HBA

### ISSUE THREAD

**Issue by dbartelmus** [im-0/hpsahba#1]
Is this necessary step to patch kernel?
I can see your git folder structure says 4.19.x.y but what about other LTS v4 kernel versions like 4.4? Can I use the same files?

I'm interested in trying your script to mess with my p410i on spare machine!

**Comment by akohlsmith** [comment]
I have a P212 connected to an external 24-bay chassis. I can enable passthrough but am struggling to get the kernel patch working with Ubuntu Xenial (kernel 4.4.0-189). I don't have tons of time to devote to it so my progress will be slow, but it looks possible to port to older kernels.

**Comment by im-0** [comment]
I have no plans for porting my patches onto older kernels and testing them, sorry. You have few options:

* use newer kernel in Ubuntu 16.04;
* upgrade to a newer Ubuntu release;
* or port and test patches yourself.
