### ISSUE TITLE
Tested and working on HP P212 controller

### ISSUE THREAD

**Issue by consp** [im-0/hpsahba#10]
I got my hands on a HP P212 card for cheap and used it for testing, it has been running for about three weeks now:

Kernel: Linux 4.19.144-hba #1 SMP Thu Sep 10 11:30:31 CEST 2020 x86_64 GNU/Linux
with hpsa.hpsa_use_nvram_hba_flag=1

```
lspci -nn -vv | grep Hewlett
02:00.0 RAID bus controller [0104]: Hewlett-Packard Company Smart Array G6 controllers [103c:323a] (rev 01)
        Subsystem: Hewlett-Packard Company Smart Array P212 [103c:3241]
```
```
./hpsahba -i /dev/sg18
VENDOR_ID='HP'
PRODUCT_ID='P212'
BOARD_ID='0x3241103c'
SOFTWARE_NAME=''
HARDWARE_NAME=''
RUNNING_FIRM_REV='6.64'
ROM_FIRM_REV='6.63'
REC_ROM_INACTIVE_REV='6.63'
YET_MORE_CONTROLLER_FLAGS='0xfa55a216'
NVRAM_FLAGS='0x08'
HBA_MODE_SUPPORTED=1
HBA_MODE_ENABLED=1
```

Currently running with two disks, both working fine and at rated speed and no errors (HGST 3TB SAS drives).

**Comment by sabatmonk** [comment]
Did you do anything special to see the drives? i did the same thing and i see nothing. dmseg show

`[    5.763641] hpsa 0000:06:00.0: scsi 0:0:0:0: added RAID              HP       P212             controller SSDSmartPathCap- En- Exp=1

[    5.763798] hpsa 0000:06:00.0: scsi 0:0:1:0: masked Direct-Access     HP       MB3000FBUCN      PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.763952] hpsa 0000:06:00.0: scsi 0:0:2:0: masked Direct-Access     ATA      ST33000651AS     PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.764105] hpsa 0000:06:00.0: scsi 0:0:3:0: masked Direct-Access     HP       MB1000FAMYU      PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.764259] hpsa 0000:06:00.0: scsi 0:0:4:0: masked Direct-Access     HP       MB3000FBUCN      PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.764412] hpsa 0000:06:00.0: scsi 0:0:5:0: masked Direct-Access     HP       MB1000FCWDE      PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.764566] hpsa 0000:06:00.0: scsi 0:0:6:0: masked Direct-Access     ATA      WDC WD10EFRX-68F PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.764732] hpsa 0000:06:00.0: scsi 0:0:7:0: masked Direct-Access     HP       MB3000FBUCN      PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.764901] hpsa 0000:06:00.0: scsi 0:0:8:0: masked Direct-Access     HP       MB3000FBUCN      PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.765058] hpsa 0000:06:00.0: scsi 0:0:9:0: masked Direct-Access     HP       MB3000FBUCN      PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.765211] hpsa 0000:06:00.0: scsi 0:0:10:0: masked Direct-Access     HP       MB3000FBUCN      PHYS DRV SSDSmartPathCap- En- Exp=0

[    5.765365] hpsa 0000:06:00.0: scsi 0:0:11:0: masked Enclosure         HP       DL18xG6BP        enclosure SSDSmartPathCap- En- Exp=0

[    5.765519] hpsa 0000:06:00.0: scsi 0:0:12:0: masked Enclosure         PMCSIERA  SRC 8x6G        enclosure SSDSmartPathCap- En- Exp=0`

and i cannot see the drives

**Comment by consp** [comment]
I don't have the card any more, did you use the same kernel or a newer one? Did you enable HBA mode with hpsa.hpsa_use_nvram_hba_flag=1 as kernel parameter?
