### ISSUE TITLE
P410 SMART Support for Drives

### ISSUE THREAD

**Issue by Fightbackman** [im-0/hpsahba#12]
Hi,
do you have any experiences with trying to gather SMART values from the drives in the controller?
I tried it, but get the following error: `/dev/sdc: requires option '-d cciss,N' `
Is there anything additional useful I can provide to you?

I'am running this on a the following (yeah I know not supported) kernel:
`Linux proxmox-test 5.4.78-2-pve #1 SMP PVE 5.4.78-2 (Thu, 03 Dec 2020 14:26:17 +0100) x86_64 GNU/Linux`
I'm going to validate this behaviour on a regular debian buster.

Thank you for this project.
I'am migrating about a dozen of server at the moment to native zfs thanks to this solution.

**Comment by Fightbackman** [comment]
It was a human error by me.

**Comment by Yardanico** [comment]
Can you please explain how you fixed that issue? I have the same error when trying to run smartctl

**Comment by Yardanico** [comment]
Oh, apparently the command should be entered just like the error says:
`sudo smartctl -d cciss,1 -a /dev/sda` where `1` is the number of a disk you want to check SMART for.

Also, when checking different disks connected to the same RAID controller you don't have to change the device path, only the disk number, so for example, if you have disks from sda to sdf, you can just do:
```
sudo smartctl -d cciss,1 -a /dev/sda
sudo smartctl -d cciss,2 -a /dev/sda
sudo smartctl -d cciss,3 -a /dev/sda
sudo smartctl -d cciss,4 -a /dev/sda
sudo smartctl -d cciss,5 -a /dev/sda
