### ISSUE TITLE
Have to run mod probe after every reboot

### ISSUE THREAD

**Issue by OMMJAI** [im-0/hpsahba#13]
I could successfully install the patch via dkms but I have to modprobe make it run automatically at every reboot

**Comment by OMMJAI** [comment]
omm@omm-VirtualBox:~$ cd /home/$USER/hpsahba
omm@omm-VirtualBox:~/hpsahba$ 
Nothing happens next

**Comment by OMMJAI** [comment]
this is done after git clone  -b dkms  https://github.com/artizirk/hpsahba

**Comment by OMMJAI** [comment]
Sorry I understood that main.c has to be converted to an executable

**Comment by OMMJAI** [comment]
Could you please tell me how to patch kernel in Debian 10

**Comment by OMMJAI** [comment]
I am trying to follow this guide

**Comment by OMMJAI** [comment]
https://medium.com/@terryjx/enable-it-mode-on-hp-smart-array-p410i-raid-card-on-hp-dl380-gen7-servers-4e827eeb78ca

**Comment by OMMJAI** [comment]
I am on debian linux 5.4
It continues to ask which file to patch (line 15)
after running command find . -type f -iname '*.patch' -print0|xargs -n1 -0 patch -p 1 -i

**Comment by OMMJAI** [comment]
I am trying to run hpsahba on a Debian VM before I try to use the tool on my Debian server.

Please tell me how to permanently patch the kernel linux 5.10 I am very new to linux please help me with the patch.

As per the GitHub page

However, to get system actually see and use disks in HBA mode, few kernel patches required
I am using these guides:

https://medium.com/@terryjx/enable-it-mode-on-hp-smart-array-p410i-raid-card-on-hp-dl380-gen7-servers-4e827eeb78ca
https://github.com/im-0/hpsahba
It continues to ask which file to patch (line 15) after running command

find . -type f -iname '*.patch' -print0|xargs -n1 -0 patch -p 1 -I
and when I try dkms I get:

make -j4 KERNELRELEASE=5.4.0-050400-generic...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.0-050400-generic (x86_64)

**Comment by gschuurman** [comment]
Running this will enable the module on boot time with the correct settings
`sudo echo "options hpsa hpsa_use_nvram_hba_flag=1" > /etc/modprobe.d/hpsa.conf`

**Comment by OMMJAI** [comment]
`sudo update-initramfs -u ` skips hpsa.conf I don’t know why

**Comment by gschuurman** [comment]
this did the trick for me.
`
sudo dkms install --force hpsa-dkms/1.0
sudo modprobe -r hpsa
sudo modprobe hpsa hpsa_use_nvram_hba_flag=1
sudo echo "options hpsa hpsa_use_nvram_hba_flag=1" > /etc/modprobe.d/hpsa.conf
sudo update-initramfs -u
`
what os are you using? perhaps that kernel looks into a different place for the config

**Comment by OMMJAI** [comment]
Debian
I fail to understand why update initramfs skips hpsa

**Comment by OMMJAI** [comment]
I will try again though

**Comment by OMMJAI** [comment]
Guys problem solved problem was that earlier I had used hips options instead of options hpsa
