### ISSUE TITLE
Documenting PSU Explosion

### ISSUE THREAD

**Issue by ohnoesIaccidentallyAPSU** [im-0/hpsahba#19]
Running gentoo on 1.10 kernel my PSU exploded on a Proliant DL380 G7 while mounting the hpsahba drives during the initramfs! Thankfully, nothing was harmed and that was a new server, with no data on it. All is well

Two things:
1. Be very careful when using this! I am not blaming this project for what happened. But, it happened nonetheless
2. IF YOU ARE USING OLD HARDWARE FOR THE LOVE OF GOD CHANGE OUT THE OLD PSU WITH SOMETHING NEW AND HIGH QUALITY. These servers are very cheap, don't skimp out on important stuff

**Comment by JKJameson** [comment]
Can we delete this issue, it's just cringe.

**Comment by ohnoesIaccidentallyAPSU** [comment]
Yes, I doubt it was caused directly by the program. Rather, a combination of factors. 
Merely a PSA... Check that your PSU is robust before using this 🤔 especially if you are using lots of drives
