### ISSUE TITLE
FATAL ERROR: Cancelled by user

### ISSUE THREAD

**Issue by recklessop** [im-0/hpsahba#2]
Im trying to run this on Ubuntu 19.04, the same place I compiled it. and I am receiving this message:

root@ubuntu:/temp/hpsahba# ./hpsahba -d /dev/sg0
 //  CAUTION  //  // CAUTION //  //  CAUTION  //  // CAUTION //  //  CAUTION  //
        HBA MODE CHANGE WILL DESTROY YOU DATA!
        HBA MODE CHANGE MAY DAMAGE YOUR HARDWARE!
Type uppercase "yes" to accept the risks and continue: yes
FATAL ERROR: Cancelled by user
root@ubuntu:/temp/hpsahba#

Any ideas?

**Comment by recklessop** [comment]
Nevermind :)

I didnt actually read and use upper case YES :)

**Comment by recklessop** [comment]
Here is what it see's now:

[   10.211032] hpsa 0000:06:00.0: can't disable ASPM; OS doesn't have ASPM control
[   10.211383] hpsa 0000:06:00.0: Logical aborts not supported
[   10.211384] hpsa 0000:06:00.0: HP SSD Smart Path aborts not supported
[   10.249090] scsi host0: hpsa
[   10.249263] hpsa can't handle SMP requests
[   10.278499] hpsa 0000:06:00.0: scsi 0:0:0:0: added RAID              HP       P410             controller SSDSmartPathCap- En- Exp=1
[   10.278502] hpsa 0000:06:00.0: scsi 0:0:1:0: masked Direct-Access     ATA      WDC WD1003FBYX-0 PHYS DRV SSDSmartPathCap- En- Exp=0
[   10.278505] hpsa 0000:06:00.0: scsi 0:0:2:0: masked Direct-Access     ATA      WDC WD1003FBYZ-0 PHYS DRV SSDSmartPathCap- En- Exp=0
[   10.278507] hpsa 0000:06:00.0: scsi 0:0:3:0: masked Direct-Access     ATA      SDLFODAR-240G-1H PHYS DRV SSDSmartPathCap- En- Exp=0
[   10.278510] hpsa 0000:06:00.0: scsi 0:0:4:0: masked Direct-Access     ATA      SDLFODAR-240G-1H PHYS DRV SSDSmartPathCap- En- Exp=0
[   10.278591] hpsa can't handle SMP requests

**Comment by dbartelmus** [comment]
So you have SATA drives.
Beside those messages, do your drives actually works?

> When HBA mode is enabled, controller usually prints some diagnostic message during boot, like "Hardware RAID support is disabled via controller NVRAM configuration settings" (example from P410i). Attempts to configure RAID arrays in this mode are expected to fail.

**Comment by recklessop** [comment]
they are sata drives. two WD Enterprise SATA disks and two Sandisk Enterprise SSD's I tried hooking the HP backplane and SAS drives i have two it, but it didnt like that.

Im wondering how i get the disks out of "Masked DIrect-Access" mode into "working mode lol
