### ISSUE TITLE
P410 or P410i?

### ISSUE THREAD

**Issue by dbartelmus** [im-0/hpsahba#4]
Will this work on integrated P410 module? or is it only for external P410i card

**Comment by JKJameson** [comment]
See README. Nobody has opened an issue or pull request confirming support for P410.

**Comment by im-0** [comment]
(just added another known-to-work controller into README)

As I understand, the only difference between P410 and P410i is that **P410** comes as a regular PCIe card, and **P410i** comes as an integrated chip (soldered on the motherboard). I successfully tested my patches with both "versions".

But note that HP never officially supported HBA mode on these controllers, and both `hpsahba` tool and patches are of "use at your own risk" quality.
