### ISSUE TITLE
CentOS 8 kernel support

### ISSUE THREAD

**Issue by andmn** [im-0/hpsahba#6]
Hi, 

the switch to HBA mode and back was successful on HP SE316M1 system with P410i card.

But I was not able to adapt your kernel patches to build a CentOS 4.18.0 custom kernel or kernel-ml 5.6.x from elrepo-kernel. As I've seen on the kernel mailing list hpsahba will not accepted. You are able to provide patches to build the custom kernel?

Thanks.

**Comment by im-0** [comment]
Hi,

try these patches with kernel-ml: https://github.com/im-0/hpsahba/tree/master/kernel/5.4. I'm successfully using them on Fedora 32 with kernel 5.6.12, which is not significantly different from the mainline kernel.

**Comment by andmn** [comment]
Thanks,
with kernel-ml it was successful. Kernel build as shown in the CentOS Wiki with 4.18 but added kernel-ml nosrc rpm to the build directory and adding patches to the kernel-ml spec file.

Also no data loss, after reboot the partition with lvm was found.
